### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by victorfreire100** [GabryeleSantoro/Telegram-Chat-Scraper#1]
hey! you can help me: 
 
 <Task finished name='Task-14' coro=<UpdateMethods._dispatch_update() done, defined at C:\Users\Escritorio\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\client\updates.py:434> exception=ValueError('Cannot find any entity corresponding to "LBR BKP"')>

**Comment by GabryeleSantoro** [comment]
Hi, have you installed all the libraries used? Seems like a telethon problem. If you have not already, use pip to install telethon.

`pip3 install telethon`

You must have pip3 installed in your system.

**Comment by victorfreire100** [comment]
Hey, your code worked great! Thanks!
